/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VideoColourAnalyser;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        VideoScanner classUnderTest = new VideoScanner();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
